user = "s-0001yebfa4ab08"
auth.token = "bfa4909f726fab08"

serverAddr = "frp-few.com"
serverPort = 8088

loginFailExit = false
transport.tls.enable = false
transport.tls.disableCustomTLSFirstByte = false

[[proxies]]
# id = 27754332
name = "WL_SSH2"
type = "tcp"

localIP = "127.0.0.1"
localPort = 22
remotePort = 14097
