name: Build-cas-miui-kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_name:
        type: choice
        options:
          - cas
          - writeurself
        description: 'Choose a device'
        required: true
        default: cas
      ksu_enabled:
        type: boolean
        description: 'Build with Kernelsu'
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false
      clean_cache:
        type: boolean
        description: 'Try clean cache if you have any compile problem'
        required: false
        default: false
      upload_artifacts:
        type: boolean
        description: 'Upload firmware to artifacts'
        required: false
        default: true
      upload_releases:
        type: boolean
        description: 'Upload firmware to releases'
        required: false
        default: true

env:
  REPO_URL: https://github.com/liyafe1997/kernel_xiaomi_sm8250_mod
  DEVICE_NAME: ${{ inputs.device_name }}
  TZ: Asia/Shanghai
  FRP_VER: 0.71.0
  OS_VER: linux

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --single-branch --depth 1 $REPO_URL
        echo "$REPO_URL" | awk -F'/' '{print "REPO_NAME="$NF}' >> $GITHUB_ENV

    - name: Relay SSH
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        echo -e "${{ secrets.RUNNER_PWD }}\n${{ secrets.RUNNER_PWD }}" | sudo passwd runner

    - name: Run Frp
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        curl -LO "https://github.com/fatedier/frp/releases/download/v${FRP_VER}/frp_${FRP_VER}_${OS_VER}_amd64.tar.gz"
        tar -xzf frp_${FRP_VER}_${OS_VER}_amd64.tar.gz
        cd frp_${FRP_VER}_${OS_VER}_amd64
        chmod +x frpc
        ./frpc -c ../frp/frpc.toml

    - name: Load Cache
      uses: WLWolf5/cachewrtbuild@android-kernel
      with:
        ccache: 'true'
        toolchain: 'true'
        mixkey: '${{ env.DEVICE_NAME }}'
        clean: '${{ inputs.clean_cache }}'
        prefix: ${{ github.workspace }}/${{ env.REPO_NAME }}

    - name: Download Clang & GCC
      if: ${{ !env.CACHE_HIT }}
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        mkdir toolchain
        cd toolchain
        ./utils/svn.sh https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 android-14.0.0_r75 clang-r487747c
        curl -LO https://gitlab.arm.com/api/v4/projects/tooling%2Fgnu-toolchains-for-arm/packages/generic/gnu-toolchain/15.3.rel1/arm-gnu-toolchain-15.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        curl -LO https://gitlab.arm.com/api/v4/projects/tooling%2Fgnu-toolchains-for-arm/packages/generic/gnu-toolchain/15.3.rel1/arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
        ls > ../cache.key
        tar -xJf arm-gnu-toolchain-15.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        tar -xJf arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz

    - name: Build Kernel
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        chmod +x build.sh
        if [ inputs.ksu_enabled ]; then
          ./build.sh ${DEVICE_NAME} ksu
        else
          ./build.sh ${DEVICE_NAME}
        fi
        echo "OUTPUT_DIR=${PWD}/output" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        
    - name: Upload firmware directory
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_artifacts }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.REPO_NAME }}_${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}
        path: ${{ env.OUTPUT_DIR }}

    - name: Generate release tag
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_releases }}
      run: |
        echo "RELEASE_TAG=${REPO_NAME}_${DEVICE_NAME}-${FILE_DATE}" >> $GITHUB_ENV
        touch release.txt

    - name: Upload firmware to release
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_releases }}
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.RELEASE_TAG }}
        bodyFile: "release.txt"
        artifacts: ${{ env.OUTPUT_DIR }}/*