name: Build Immortalwrt for MT7981 devices

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device_name:
        type: choice
        options:
          - wr30u
          - unknow
        description: 'Choose a device'
        required: true
        default: wr30u
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false
      upload_artifacts:
        type: boolean
        description: 'Upload firmware to artifacts'
        required: false
        default: true
      upload_releases:
        type: boolean
        description: 'Upload firmware to releases'
        required: false
        default: true

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  TZ: Asia/Shanghai
  FRP_VER: 0.69.1
  OS_VER: linux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --single-branch --depth 1 --filter=blob:none $REPO_URL
        echo "$REPO_URL" | awk -F'/' '{print "REPO_NAME="$NF}' >> $GITHUB_ENV
        cd ${{ env.REPO_NAME }}
        echo "REPO_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Install feeds
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load .config file
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        cp defconfig/mt7981-ax3000.config .config

    - name: Load custom scripts
      working-directory: ./mywrt/custom
      run: |
        chmod +x third-party.sh
        ./third-party.sh
        chmod +x patch.sh
        ./patch.sh

    - name: Load extra packages
      working-directory: ./mywrt
      run: |
        cp -r luci ${{ env.REPO_DIR }}/package/addons

    - name: Relay SSH
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        echo -e "${{ secrets.USER_PWD }}\n${{ secrets.USER_PWD }}" | sudo passwd runner
        
    - name: Run Frp
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        curl -LO "https://github.com/fatedier/frp/releases/download/v"$FRP_VER"/frp_"$FRP_VER"_"$OS_VER"_amd64.tar.gz"
        tar -xzf frp_"$FRP_VER"_"$OS_VER"_amd64.tar.gz
        cd frp_"$FRP_VER"_"$OS_VER"_amd64
        chmod +x frpc
        ./frpc -c ../frp/frpc.toml

    - name: Build/Load Cache
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        toolchain: 'true'
        mixkey: 'mediatek'
        clean: 'false'
        prefix: ${{ github.workspace }}/${{ env.REPO_NAME }}

    - name: Download packages
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      working-directory: ./${{ env.REPO_NAME }}
      run: |
        echo -e "$(nproc) threads ready"
        make -j$(nproc) || make -j1 || make -j1 V=s
        DEVICE_NAME="$(ls bin/targets/mediatek/filogic | grep squashfs-sysupgrade.bin | awk '{sub(/immortalwrt-mediatek-filogic-/,"");sub(/-squashfs-sysupgrade\.bin$/,"");print}')"
        echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
        BIN_DIR="$(pwd)/bin/targets/mediatek/filogic"
        echo "BIN_DIR=${BIN_DIR}" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

    - name: Upload firmware directory
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_artifacts }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.REPO_NAME }}_${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}
        path: ${{ env.BIN_DIR }}

    - name: Generate release tag
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_releases }}
      run: |
        echo "RELEASE_TAG=${{ env.REPO_NAME }}_${{ env.DEVICE_NAME }}" >> $GITHUB_ENV
        touch release.txt

    - name: Upload firmware to release
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_releases }}
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.RELEASE_TAG }}
        bodyFile: "release.txt"
        artifacts: ${{ env.BIN_DIR }}/*

#    - name: if failure
#      if: ${{ failure() }}
#      run: |
